spring.application.name=solicitudes

spring.datasource.url=jdbc:sqlserver://10.2.0.6:1433;databaseName=PortalSolicitudes;encrypt=true;trustServerCertificate=true
spring.datasource.username=safeadmin
spring.datasource.password=R3s0Urc3s2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Nombre que se muestra en el codigo QR de los autenticadores
app.2fa.issuer=SDR Safe Data - Portal de Solicitudes

# Dias/meses de expiracion de contrasena
app.password.expiracion-dias=90

# ===== SMTP (mail.archivos.com.mx) =====
spring.mail.host=mail.archivos.com.mx
spring.mail.port=465
spring.mail.username=terminal@archivos.com.mx
spring.mail.password=SDR&1995te@+
spring.mail.default-encoding=UTF-8

# Puerto 465 => SSL implicito (NO STARTTLS)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# Timeouts (los mismos que pusiste en Android)
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=60000
spring.mail.properties.mail.smtp.writetimeout=60000

# Remitente visible
app.mail.from=terminal@archivos.com.mx
app.mail.from-name=SafeData Reportes

# URL base del portal (cambia en produccion)
app.url-base=http://localhost:8080